### ISSUE TITLE
CH Products - CH Force FX joystick USB support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tloimu/adapt-ffb-joy#14]
```
1.Full USB conversion for the CH Force FX stick - with full force feedback, 
just like can be achieve with the current setup with a MS FFB Pro stick.


2. Those to benefit are ones with old serial port CH Force FX sticks.  Gamers, 
and sim pit hobbyists.  I have two new CH Force FX sticks - still boxed new.




```

Original issue reported on code.google.com by `jonnyred...@gmail.com` on 30 May 2014 at 10:02

**Comment by kfix** [comment]
This patent describes the Exos/Sidewinder MIDI protocol:
https://www.google.com/patents/US5742278

These describe in some detail the workings of the CHFX and IFORCE 1.0:
https://www.google.com/patents/US5734373
https://patents.google.com/patent/US6424356B2
https://patents.google.com/patent/US6169540B1
http://www.driverguide.com/driver/detail.php?driverid=137120&action=filfo

**Comment by kfix** [comment]
I have found a copy of Immersion's [DX5 & I-Force 2.0 programming guide](https://ptabdata.blob.core.windows.net/files/2017/IPR2017-00896/v15_Exhibit-1017-Rosenberg-A-Force-Feedback-Programming-Primer.pdf), courtesy of Apple Inc's patent litigators.

However, the Force FX [appears](http://bbs.hitechcreations.com/smf/index.php/topic,29575.msg310029.html#msg310029) to be a 1.0 device:
> CH Products and Immersion have ceased to support the CH Force FX because it's an I-force 1 device, whereas the current FF sticks use the I-force 2 API. 

> I-force 1->2 "translating" drivers for DirectX use were released and supported until mid-1998, but now there will not be any more DirectX driver updates. The latest drivers are from July 1998 and were written for DirectX 5. (Quitting all support like this is infuriating because the stick has only been around for 3-4 years or so, and is so bomb-proof that it will last a lifetime - and it's an excellent stick too, allowing external pedals and throttle without any problems, making it the stick of choice for many hardcore flight-sim enthusiasts).

**Comment by tloimu** [comment]
This would require the same reverse engineering work to determine the protocol used for relaying the effects to the stick. Work that requires having the actual stick and a pre-Windows 7 installation with CH drivers to drive it and to allow live analysis of the CH's protocol.

I don't have the stick nor the drivers to do that so that work would need to be done within some other research project.

**Comment by qurbat** [comment]
@kfix @tloimu have you looked at https://github.com/timschumi/iforce-binary-driver?

**Comment by qurbat** [comment]
@kfix @tloimu you should look at https://github.com/timschumi/iforce-binary-driver
