### ISSUE TITLE
Does this supercede r54 from google code ?

### ISSUE THREAD

**Issue by extremeshok** [tloimu/adapt-ffb-joy#17]
I installed r54 from the google code a while ago onto my MS Force Sidewindewr Feedback Pro with a teensy 2.0 ATmega32U4

Does this version supersede that ? and is it supported on my teensy ?

**Comment by Poil** [comment]
This is just a sync of google code before they close.

**Comment by laurentd75** [comment]
Hi Poil, since you gave a clear answer to extremeshok's question,  I think this issue should now be closed :-)

Leaving this issue open can only cause confusion and make people think the question is unresolved :-)

**Comment by tloimu** [comment]
Agreed, closing.
