### ISSUE TITLE
Sidewinder FFB cable color code

### ISSUE THREAD

**Issue by xforce22** [tloimu/adapt-ffb-joy#18]
Hi

I broke my FFBs gameport plug, and want to resolder it to a new one ,.
Does anyone know the color code? Meaning which color wire goes to which pin of the gameport?

**Comment by Poil** [comment]
Hey;

Here :
http://www.descentbb.net/viewtopic.php?f=8&t=19061&sid=2b3e3a82cdf39346cff3833d536305fe&start=240

Br

**Comment by tloimu** [comment]
The answer is behind the link in the DescentBB forum.
