### ISSUE TITLE
Circuit Diagram in HowToBuild.md not found

### ISSUE THREAD

**Issue by dlwalter** [tloimu/adapt-ffb-joy#19]
Clicking on the link for the circuit diagram goes to a 'not found' page.

http://adapt-ffb-joy.googlecode.com/files/adaptffbjoy-circuit.png

Located on https://github.com/tloimu/adapt-ffb-joy/blob/wiki/HowToBuild.md

**Comment by schmatzler** [comment]
Here's the file in case anyone needs it:

![adaptffbjoy-circuit](https://user-images.githubusercontent.com/1711691/36924530-42e8e072-1e6f-11e8-8a61-88fa269120ce.png)

**Comment by schmatzler** [comment]
@Poil restored all of the missing images in his fork:

https://github.com/Poil/adapt-ffb-joy/commit/0f6614bbac89cbe4b5a01f06ecb1e401c46e1fb3

**Comment by tloimu** [comment]
Fixed the image link and a couple of other similar. The problem was the Google Code's port to Git that it didn't take into account the links withing the site.
