### ISSUE TITLE
Only LED blinking, need help.

### ISSUE THREAD

**Issue by gh0stless** [tloimu/adapt-ffb-joy#24]
please.

-andreas

**Comment by AndiTheBest** [comment]
Same here. You also have the wheel?
With a hex-file from the 3dp-vert project, my wheel gets recognized by the PC, but the mappings are not usable.

**Comment by gh0stless** [comment]
Hi Andi,
do you have a link to this .hex file for me?

**Comment by gh0stless** [comment]
OK, solved. I was removing the C1 & C2 and it is working now.
