### ISSUE TITLE
X, Y axis movement also slightly affects Z rotation

### ISSUE THREAD

**Issue by cbhacking** [tloimu/adapt-ffb-joy#28]
FFB Pro joystick, Win10.

Moving the stick forward and back slightly affects the Z-axis rotation (forward decreases rotation as though twisting counter-clockwise, pulling back increases as though twisting clockwise). Left and right movement of the stick also has some effect, though much subtler (forward-right corner shows approximately the expected rotation value, but center-right is only very slightly higher than expected).

The forward-center movement is the most dramatic in terms of impact on the Z rotation, changing it by upwards of 20% (enough to induce noticeable yaw unless I set a very large dead zone). Other directions are smaller effects, though still visible. This change happens whether or not FFB is active, including when it is unpowered and I'm simply pushing the stick with one finger (not gripping it at all). When gripping, I can override this rotation, but it does require fighting the spring force. I can also still move through the entire Z rotation range by twisting the stick the appropriate direction, so it's usable for flying, but not great.

It's possible, of course, that this is simply due to the age of the stick and has nothing to do with the adapter or its firmware. However, I'd like to see if this can be fixed in the adapter firmware. I don't have either another version of this stick or any PC with a native gameport to test with.

**Comment by TomHVR** [comment]
The stick has an optical sensor (like a literal camera) used for tracking all axis. Maybe there is debris/dust on the camera sensor that's causing it to misread the z axis as it's moving around?

https://youtu.be/wVMvXAtynp0?t=105
