### ISSUE TITLE
Microsoft provided adapter

### ISSUE THREAD

**Issue by isopix** [tloimu/adapt-ffb-joy#31]
Hi,

Common knowledge claims it was not USB compatible and there were no USB adapter provided by Microsoft (unlike for non-force feedback version)

But this seller claims otherwise:
[https://www.ebay.pl/itm/114603270740](https://www.ebay.pl/itm/114603270740)

He even sent me reply, will cite fragment of it there:

> The game controller came in origin with this adaptor, it was built for use with the old game port and with the new USB port (new in 80/90’ years). I used both and they worked smoothly. And it’s still working. The controller is heavy, rock solid and 100% working with USB port

If it's true, then it would be nice to reverse-engineer the original adapter (maybe firmware is dumpable).
If it would be multiple times cheaper, I would buy it. But it's not :-/

**Comment by Poil** [comment]
This adapter is for the non ffb, I have it too.
