### ISSUE TITLE
Need help for arduino pro micro solution found !!!

### ISSUE THREAD

**Issue by drepou** [tloimu/adapt-ffb-joy#35]
Hi is there anyone who make work the .hex on arduino pro micro ? 

###  **it work for me  found the issue and solution the 1nf condensator on PB5 is mandatory with my ffb1 96755. If not present the mode "digital" is not decteted during initialisation by the stick and effect are not taken in consideration.**

more info on init process here : https://www.descentbb.net/viewtopic.php?f=8&t=19061

history of what i have done :

the pinout is not the same on the board so i just "moved" the connection with same name beetween the two boards 

i dont have the PB0 on the pro micro board so i didnt make the PB0-PD0 connection may be my mistake then desolder the smd resistor on TX led i use the pad has PB0 pad and solder it with PD0 as need. No FFB even with that.

Note for other guys who can have issue like me :
PD0 look to have two différents places pin3 and pin14 based on https://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/ProMicro16MHzv1.pdf

**--> ok i found the answer PD0 is on PIN3 for my micro pro**  check with 32u4 pinout to confirm.

I use the old ffb1 sidewinder 96755 i noticed that if i just plug the 12v adapter on the stick but no connected the gameport 
i have no reaction of the stick no self centering and no resistance it look to be the normal behaviour
i was thinking that plug the power will center the stick if not connected to a PC but that is not the case.

First try my stick was well  detected by windows but reading value and force produced eractic value reading are very unstable.
 Pov bouton is always "on" for one direction  :  

**found the issue it was because i didnt connected all the wire after adding pb2 and pb3 the reading value where correct and stable. Only Z is a bit eratic.

I used adaptffbjoy-r54-Clean.hex found here :  https://github.com/JayBee-git/adapt-ffb-joy/tree/master/downloads

Flashed with avrdude who came with ide arduino ( took the line code from verbose flash log in ide and changed the name of the HEX to my.  You need to reset the arduino micro just before flash by but gnd on "reset" pin for short time just before : the com port is not the one see by default on IDE this is normal... keep the same from verbose log of your arduino ide when you flash .ino from ide

example :

C:\Users\drepou\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/bin/avrdude -CC:\Users\drepou\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf -v -patmega32u4 -cavr109 -PCOM6 -b57600 -D -Uflash:w:C:\hex/adaptffbjoy-r54-Clean.hex:i 

Arduino micro is not detected by window after flash if no joystick is connected on it i confirm that too !

I have checked the midi output on pin 12 ( gameport ) look that the protocol is correct no idea why the stick not react : 

Sample of Constant force send with Force Editor :

Time [s],Value
-0.000032000000000,PatchChange Channel: 5,0xC5
0.000288000000000,InstrumentNum Channel: 5 [0x01],0x01
0.077033250000000,PatchChange Channel: 5,0xC5
0.077353250000000,InstrumentNum Channel: 5 [0x01],0x01
0.147097250000000,ContinuousController Channel: 5,0xB5
0.147417250000000,ControllerNum Channel: 5 [0x01],0x7C
0.147737500000000,ControllerValue Channel: 5 [0x01],0x7F
0.148057500000000,Aftertouch Channel: 5,0xA5
0.148377500000000,Key Channel: 5 [0x01],0x7F
0.148697500000000,Touch Channel: 5 [0x01],0x00
0.149017750000000,PatchChange Channel: 5,0xC5
0.149337750000000,InstrumentNum Channel: 5 [0x01],0x06
3.351471250000000,BeginSystemExclusiveMessage,0xF0
3.351791500000000,orphanedData Channel: -2 [0x01],0x00
3.352111500000000,orphanedData Channel: -2 [0x01],0x01
3.352431500000000,orphanedData Channel: -2 [0x01],0x0A
3.352751500000000,orphanedData Channel: -2 [0x01],0x01
3.353071500000000,orphanedData Channel: -2 [0x01],0x23
3.353391750000000,orphanedData Channel: -2 [0x01],0x12
3.353711750000000,orphanedData Channel: -2 [0x01],0x7F
3.354031750000000,orphanedData Channel: -2 [0x01],0x7B
3.354351750000000,orphanedData Channel: -2 [0x01],0x17
3.354672000000000,orphanedData Channel: -2 [0x01],0x00
3.354992000000000,orphanedData Channel: -2 [0x01],0x00
3.355312000000000,orphanedData Channel: -2 [0x01],0x00
3.355632000000000,orphanedData Channel: -2 [0x01],0x00
3.355952000000000,orphanedData Channel: -2 [0x01],0x7F
3.356272250000000,orphanedData Channel: -2 [0x01],0x64
3.356592250000000,orphanedData Channel: -2 [0x01],0x00
3.356912250000000,orphanedData Channel: -2 [0x01],0x10
3.357232250000000,orphanedData Channel: -2 [0x01],0x4E
3.357552250000000,orphanedData Channel: -2 [0x01],0x7F
3.357872500000000,orphanedData Channel: -2 [0x01],0x00
3.358192500000000,orphanedData Channel: -2 [0x01],0x00
3.358512500000000,orphanedData Channel: -2 [0x01],0x7F
3.358832500000000,orphanedData Channel: -2 [0x01],0x7B
3.359152750000000,orphanedData Channel: -2 [0x01],0x17
3.359472750000000,orphanedData Channel: -2 [0x01],0x7F
3.359792750000000,orphanedData Channel: -2 [0x01],0x01
3.360112750000000,orphanedData Channel: -2 [0x01],0x00
3.360432750000000,orphanedData Channel: -2 [0x01],0x7F
3.360753000000000,orphanedData Channel: -2 [0x01],0x00
3.361073000000000,orphanedData Channel: -2 [0x01],0x00
3.361393000000000,orphanedData Channel: -2 [0x01],0x00
3.361713000000000,orphanedData Channel: -2 [0x01],0x6A
3.362033250000000,EndSystemExclusiveMessage,0xF7
9.501357000000000,ContinuousController Channel: 5,0xB5
9.501677000000001,ControllerNum Channel: 5 [0x01],0x20
9.501996999999999,ControllerValue Channel: 5 [0x01],0x02

Last action add the optional condensator make the FFB work !!!! GREAT thanks to all Develloper

**Comment by drepou** [comment]
solution found please see my  auto comment

**Comment by shearn89** [comment]
Just to say a massive thank you for this! Was tearing my hair out with @juchong's fork thinking it would just work - but on my Pro Micro USB C version, the pin for PD0 was also off by one - had to be pin 3 or 10 as labelled on the pro micro, due to the fact they're connected. I now have a working joystick!!

**Comment by juchong** [comment]
> 

No problem! I'm glad to hear my fork has helped others!

**Comment by shearn89** [comment]
@juchong - while I have you here - do you know if the 'shake' effects on e.g. aircraft stall work with your fork? I have a Sidewinder Force Feedback Pro (1, not 2), and get no stall effects or ground rumble in DCS. Any ideas? I've tried with a force feedback test app and the 'sine wave' effect does nothing...

**Comment by ej113** [comment]
Sine waves work for me. I tested with fedit and also with FS-Force in FSX. I could recognise nearly all of the effects I was expecting from the FS-Force documentation. However I did observe that any effect with less than about 40% gain was imperceptible, so I had to dial up most of the effect gains in software, otherwise they were too subtle. Might just be because my FFBP needs a service though. This wouldn't explain why you are getting no response in the test app however. Are you sure you're getting any effects other than the default spring centering?

**Comment by shearn89** [comment]
I'll give it another try this evening with various apps. In the test app I was using I was able to see constant force, return to centre, damping - all worked fine. But sine wave didn't. Also in game I don't get any shake effects but I've heard reports that the FFB Pro 2 does... I'll try and do some more digging though.

Do you have DCS World (it's free for the base game)? If so, can you hop in the free TF-51D and let me know how it feels?

I guess it might be down to the game, not the firmware!

**Comment by shearn89** [comment]
Okay - interestingly, this evening using some ForceTest.exe - none of the effects take hold. The stick is stuck in 'spring center' mode, when the other day I could get most of the options like 'constant force' to work and move the stick. I've also tried FEdit and set up a simple sine wave - no luck eiher! I'm planning on converting my breadboard setup to a more permanent protoboard setup, so will report back then. It may be some dodgy connections on the breadboard...

**Comment by MacGH23** [comment]
Perhaps you need a bigger cap like me.
See
https://github.com/tloimu/adapt-ffb-joy/issues/20#issuecomment-2126491248
