### ISSUE TITLE
Its not really an "Issue" but rather me trying to get smart people to help me get this working with a full sized arduino...

### ISSUE THREAD

**Issue by ZeroTasteGuy** [tloimu/adapt-ffb-joy#37]
Hi there, i have been trying to get my dads old sidewinder ff pro working again for a while now and have yet to be successful... i bought an gameport to usb adapter but its not "working" and while i was trying to troubleshoot that i stumbled across this lovely project. Now after reading through it i wanted to see if some of the "smarter" people here could help me get it working on my hardware

**Comment by ZeroTasteGuy** [comment]
https://cdn.discordapp.com/attachments/750058894188871702/947456688255029268/IMG_20220227_123327.jpg
https://cdn.discordapp.com/attachments/750058894188871702/947456688628318238/IMG_20220227_123237.jpg

**Comment by ZeroTasteGuy** [comment]
this is the part of the adapter i plan on using

**Comment by aleraco** [comment]
Aleraco@gmail.com

**Comment by ZeroTasteGuy** [comment]
> [Aleraco@gmail.com](mailto:Aleraco@gmail.com)

what?

**Comment by aleraco** [comment]
I can give you help if you give me you mail

**Comment by ZeroTasteGuy** [comment]
> I can give you help if you give me you mail

zerotasteguy@gmail.com

**Comment by tloimu** [comment]
Moved to discussion side as https://github.com/tloimu/adapt-ffb-joy/discussions/38
